#pragma once

#include "NativeGameplayTags.h"

namespace CG_GameplayTags
{
	// Weapon hands
	CLOSEDGROUNDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CG_WeaponHand_Right);
	CLOSEDGROUNDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CG_WeaponHand_Left);
	// Regions
	CLOSEDGROUNDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CG_Region_MixedForest);
	CLOSEDGROUNDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CG_Region_FlowerForest);
	CLOSEDGROUNDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CG_Region_Lake);
	CLOSEDGROUNDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CG_Region_RockyHills);
	CLOSEDGROUNDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CG_Region_EastSwamp);
	CLOSEDGROUNDS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CG_Region_WestSwamp);
}
