;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayCue.HitReaction.Attack.Melee",DevComment="")
+GameplayTagList=(Tag="GameplayCue.HitReaction.Enemy",DevComment="")
+GameplayTagList=(Tag="GAS.Ability.Jump",DevComment="")
+GameplayTagList=(Tag="GAS.Cooldown.Attack",DevComment="")
+GameplayTagList=(Tag="GAS.Data.AttackSpeed",DevComment="")
+GameplayTagList=(Tag="GAS.Effect.Consuming",DevComment="")
+GameplayTagList=(Tag="GAS.Effect.Heal",DevComment="")
+GameplayTagList=(Tag="GAS.Effect.Poison.Antidotum",DevComment="")
+GameplayTagList=(Tag="Quest.ClearingRubbishFromTheForest",DevComment="")
+GameplayTagList=(Tag="Quest.ClearingRubbishFromTheForest.Rubbish",DevComment="")
+GameplayTagList=(Tag="Quest.FindACampfire",DevComment="")
+GameplayTagList=(Tag="Quest.FindAHive",DevComment="")
+GameplayTagList=(Tag="Quest.FindAWell",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Campfire",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.ClearingRubbishFromTheForest.Rubbish",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Fontain",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Hive",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Rubbish",DevComment="")
+GameplayTagList=(Tag="Quest.Objective.Well",DevComment="")

